package tokenizer

var stopWords = map[string]interface{}{
	"i": nil, "me": nil, "my": nil, "myself": nil, "we": nil, "our": nil, "ours": nil, "ourselves": nil,
	"you": nil, "your": nil, "yours": nil, "yourself": nil, "yourselves": nil, "he": nil, "him": nil,
	"his": nil, "himself": nil, "she": nil, "her": nil, "hers": nil, "herself": nil, "it": nil, "its": nil,
	"itself": nil, "they": nil, "them": nil, "their": nil, "theirs": nil, "themselves": nil, "what": nil,
	"which": nil, "who": nil, "whom": nil, "this": nil, "that": nil, "these": nil, "those": nil, "am": nil,
	"is": nil, "are": nil, "was": nil, "were": nil, "be": nil, "been": nil, "being": nil, "have": nil,
	"has": nil, "had": nil, "having": nil, "do": nil, "does": nil, "did": nil, "doing": nil, "a": nil,
	"an": nil, "the": nil, "and": nil, "but": nil, "if": nil, "or": nil, "because": nil, "as": nil,
	"until": nil, "while": nil, "of": nil, "at": nil, "by": nil, "for": nil, "with": nil, "about": nil,
	"against": nil, "between": nil, "into": nil, "through": nil, "during": nil, "before": nil, "after": nil,
	"above": nil, "below": nil, "to": nil, "from": nil, "up": nil, "down": nil, "in": nil, "out": nil,
	"on": nil, "off": nil, "over": nil, "under": nil, "again": nil, "further": nil, "then": nil, "once": nil,
	"here": nil, "there": nil, "when": nil, "where": nil, "why": nil, "how": nil, "all": nil, "any": nil,
	"both": nil, "each": nil, "few": nil, "more": nil, "most": nil, "other": nil, "some": nil, "such": nil,
	"no": nil, "nor": nil, "not": nil, "only": nil, "own": nil, "same": nil, "so": nil, "than": nil,
	"too": nil, "very": nil, "account": nil, "balance": nil, "payment": nil, "deposit": nil,
	"withdrawal": nil, "transaction": nil, "reference": nil, "remittance": nil, "clearing": nil,
	"mortgage": nil, "investment": nil, "service": nil, "installment": nil, "loan": nil, "insurance": nil,
	"success": nil, "failed": nil, "complete": nil, "pending": nil, "canceled": nil, "processed": nil,
	"processing": nil, "approved": nil, "declined": nil, "authorized": nil, "unauthorized": nil,
	"reversed": nil, "charged": nil, "credited": nil, "debited": nil, "posted": nil, "adjustment": nil,
	"reversal": nil, "final": nil, "initial": nil, "settled": nil, "unsettled": nil, "usd": nil,
	"idr": nil, "eur": nil, "inr": nil, "gbp": nil, "jpy": nil, "cny": nil, "amount": nil,
	"fee": nil, "commission": nil, "interest": nil, "principal": nil, "credit": nil, "return": nil,
	"tax": nil, "penalty": nil, "fine": nil, "invoice": nil, "receipt": nil, "voucher": nil,
	"saya": nil, "kamu": nil, "dia": nil, "kami": nil, "kita": nil, "mereka": nil, "ini": nil, "itu": nil,
	"apa": nil, "siapa": nil, "dimana": nil, "kapan": nil, "mengapa": nil, "bagaimana": nil, "adalah": nil,
	"ialah": nil, "dan": nil, "atau": nil, "tapi": nil, "tetapi": nil, "dengan": nil, "dari": nil, "di": nil,
	"pada": nil, "untuk": nil, "sebagai": nil, "karena": nil, "bahwa": nil, "bukan": nil, "ya": nil,
	"tidak": nil, "maupun": nil, "juga": nil, "hanya": nil, "saja": nil, "setiap": nil, "lebih": nil,
	"kurang": nil, "banyak": nil, "sedikit": nil, "selama": nil, "hingga": nil, "antara": nil, "setelah": nil,
	"sebelum": nil, "sehingga": nil, "agar": nil, "supaya": nil, "oleh": nil, "pasti": nil, "sudah": nil,
	"belum": nil, "akan": nil, "mau": nil, "pernah": nil, "mungkin": nil, "harus": nil,
	"rekening": nil, "saldo": nil, "transfer": nil, "kredit": nil, "debit": nil, "pembayaran": nil,
	"setoran": nil, "penarikan": nil, "transaksi": nil, "referensi": nil, "bank": nil, "atm": nil,
	"biaya": nil, "charge": nil, "refund": nil, "remitansi": nil, "kliring": nil, "settlement": nil,
	"bunga": nil, "pinjaman": nil, "hipotek": nil, "investasi": nil, "angsuran": nil, "asuransi": nil,
	"pajak": nil, "denda": nil, "sdr": nil, "sdri": nil, "bpk": nil, "ibu": nil, "tn": nil, "ny": nil,
	"bapak": nil, "jenius": nil, "jeniuspay": nil, "sag": nil, "se": nil, "sh": nil, "sip": nil,
	"skep": nil, "skom": nil, "spd": nil, "spsi": nil, "ssi": nil, "ssos": nil, "st": nil, "dr": nil, "drs": nil,
	"ir": nil, "prof": nil, "mt": nil, "msi": nil, "bsc": nil, "msc": nil, "meng": nil, "mba": nil,
	"phd": nil, "journal": nil, "trf": nil, "pak": nil, "mas": nil, "dek": nil, "lain": nil, "cr": nil,
	"switching": nil, "sdra": nil, "januari": nil, "februari": nil, "maret": nil, "april": nil, "mei": nil,
	"juni": nil, "juli": nil, "agustus": nil, "september": nil, "oktober": nil, "nopember": nil, "desember": nil,
	"note": nil, "ke": nil, "kepada": nil, "admin": nil, "via": nil, "flip": nil,
}
